targets:
  $default:
    builders:
      objectbox_generator|objectbox:
        enabled: true
        options:
          # This is the default, you can remove this section
          # if you want to use the default location
          output_dir: lib/src/objectbox 