name: Notematic
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: 1.0.8
  http: 1.5.0
  shared_preferences: 2.5.3
  logger: 2.6.1
  flutter_staggered_grid_view: 0.7.0
  package_info_plus: 8.3.1
  flutter_dotenv: 5.2.1
  uuid: 4.5.1
  flutter_riverpod: 2.6.1
  riverpod_annotation: 2.6.1
  drift: 2.28.1
  google_fonts: ^6.2.1
  path_provider: ^2.1.5
  path: ^1.9.0
  meta: 1.16.0
  sqlite3_flutter_libs: ^0.5.0
  google_sign_in: 7.1.1
  flutter_quill: ^11.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 6.0.0
  build_runner: 2.4.15
  riverpod_generator: 2.6.5
  drift_dev: 2.28.0
  mocktail: ^1.0.3
flutter:
  uses-material-design: true
  assets:
    - .env
    - oauth/
