name: notematic_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: 1.0.8
  http: 1.4.0
  shared_preferences: 2.5.3
  logger: 2.6.0
  flutter_staggered_grid_view: 0.7.0
  package_info_plus: 8.3.0
  google_sign_in: 7.1.0
  flutter_dotenv: 5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env
