// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class Note {
  final String? id;
  final String? rev;
  final String userId;
  final String notebookId;
  final String title;
  final String content;
  final String createdAt;
  final String updatedAt;

  const Note({
    this.id,
    this.rev,
    required this.userId,
    required this.notebookId,
    required this.title,
    required this.content,
    required this.createdAt,
    required this.updatedAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      rev.hashCode ^
      userId.hashCode ^
      notebookId.hashCode ^
      title.hashCode ^
      content.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Note &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          rev == other.rev &&
          userId == other.userId &&
          notebookId == other.notebookId &&
          title == other.title &&
          content == other.content &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt;
}
