// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class Notebook {
  final String? id;
  final String? rev;
  final String userId;
  final String name;
  final String? description;
  final String? color;
  final String createdAt;
  final String updatedAt;

  const Notebook({
    this.id,
    this.rev,
    required this.userId,
    required this.name,
    this.description,
    this.color,
    required this.createdAt,
    required this.updatedAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      rev.hashCode ^
      userId.hashCode ^
      name.hashCode ^
      description.hashCode ^
      color.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Notebook &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          rev == other.rev &&
          userId == other.userId &&
          name == other.name &&
          description == other.description &&
          color == other.color &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt;
}
