// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../models/auth.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `decode_token`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `Claims`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `fmt`

Future<AuthResponse> registerUser({
  required String username,
  required String email,
  required String password,
}) => RustLib.instance.api.crateApiAuthRegisterUser(
  username: username,
  email: email,
  password: password,
);

Future<AuthResponse> loginUser({
  required String username,
  required String password,
}) => RustLib.instance.api.crateApiAuthLoginUser(
  username: username,
  password: password,
);

Future<AuthResponse> refreshUserToken({required String refreshToken}) => RustLib
    .instance
    .api
    .crateApiAuthRefreshUserToken(refreshToken: refreshToken);

Future<String> greet({required String name}) =>
    RustLib.instance.api.crateApiAuthGreet(name: name);
