// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../models/note.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<Note> createNote({
  required String accessToken,
  required String notebookId,
  required String title,
  required String content,
}) => RustLib.instance.api.crateApiNoteCreateNote(
  accessToken: accessToken,
  notebookId: notebookId,
  title: title,
  content: content,
);

Future<List<Note>> getNotebookNotes({required String notebookId}) =>
    RustLib.instance.api.crateApiNoteGetNotebookNotes(notebookId: notebookId);
