// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../models/notebook.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<Notebook> createNotebook({
  required String accessToken,
  required String name,
  String? description,
  String? color,
}) => RustLib.instance.api.crateApiNotebookCreateNotebook(
  accessToken: accessToken,
  name: name,
  description: description,
  color: color,
);

Future<List<Notebook>> getUserNotebooks({required String accessToken}) =>
    RustLib.instance.api.crateApiNotebookGetUserNotebooks(
      accessToken: accessToken,
    );
